repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix]
        types: [text]
        files: \.(json|template)$
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.2
    hooks:
      - id: check-jsonschema
        files: "config.json"
        args: ["--schemafile", "config-schema.json"]
